(function(document) {
    [
"Vodka is incredibly flavorful.",
"As soon as it hits my tongue, I’m hit with what I can best describe as creamy vanilla and almond.",
"It’s very, very rare that I find flavors so pronounced in an unflavored vodka, so I’m not being hyperbolic when I talk about the richness of flavor.",
"The vodka itself is very smooth in the mouth with no harshness on the swallow.",
"There are only a handful of vodkas I have tried that I consider to be sipping vodkas.",
"Normally when I call something a sipping vodka, it’s because the vodka has no flavor and is as easy to drink as water.",
"In this case, vodka is a great sipping vodka because it doesn’t taste like water.",
"The flavor profile is so pleasant straight that there’s really no point in mixing the vodka with anything except a little ice.",
"Vodka adds an interesting twist to the ice pick.",
"It’s very smooth and tastes great, but the vanilla-almond flavor of the vodka fully changes the taste of the tea.",
"The flavor change of adding vodka to sweet tea is as big of a flavor change as adding lemon to sweet tea.",
"It’s very hard to explain the flavor, but it punches up some of the sweetness and the almond notes adds something savory to the cocktail.",
"It’s definitely not my normal ice pick, but it is a very good rendition.",
"I also mixed one part vodka with one part orange juice and one part pomegranate juice.",
"I was a little worried that the robust flavor of vodka would get in the way of the fruit juices, but I was very wrong.",
"Vodka made this cocktail amazing.",
"It’s the best incarnation of the cocktail I’ve ever had.",
"The creamy vanilla flavors reduced the tartness of the pomegranate, allowing the sweetness to really come through.",
"The vodka didn’t activate any bitterness in the orange juice.",
"This combination is simply delectable.",
"I’m no mixologist but I expect that vodka would be an incredible tool in the right hands.",
"I’m looking forward to hearing what sort of signature cocktails are developed around this vodka.",
"Vodka is a vodka unlike any other I have tried.",
"The flavors are so undeniably rich that it is impossible to compare this vodka with any other vodka on the market.",
"It’s very smooth straight and mixes well.",
"Vodka is not typical.",
"It’s exceptional.",
"The shot is smooth.",
"Man, oh, man, it’s smooth.",
"The taste is sweet and barely there.",
"This is the closest to a true ethanol / water mixture I’ve tasted.",
"It goes down with no burn and no bitter aftertaste.",
"White grape pomegranate again.",
"Vodka is like candy mixed.",
"There is only a slight hint of the flavor.",
"Everything else tastes quite natural.",
"The shot is clean in the mouth.",
"There are no noticeable flavors.",
"The shot goes down smooth with a mild burn left on the tongue that slowly reveals itself over a period of several seconds.",
"I haven’t even contemplated a chaser.",
"This is a great straight vodka.",
"The clear taste of the shot is echoed in the White Grape Pomegranate mixed drink.",
"At a moderate mix, the cocktail is easily drinkable, and even chugable if you’re in a hurry.",
"Even at a higher 50/50 mix, the drink is acceptable, though the contrasting ingredients come off a little bitter.",
"Like straight, vodka is a great mixing vodka.",
"The shot immediately burns and floods the mouth with a taste that leads to eye-squenching and mouth puckering.",
"I felt the hangover coming on as the shot scratched down my throat and the chills ran up my back.",
"This isn’t a shooting vodka.",
"We had picked up Zero Carb Rockstar, since we’d never seen it before.",
"It’s the pink version of Sugar Free Rockstar.",
"It’s a good mixer, and vodka blends with it well.",
"The vodka doesn’t overpower the mixer, though the tart tinge of less-than-perfectly distilled vodka is detectable.",
"Overall, the mix is easy to swallow and pretty nice to drink.",
"I’ve had vodka at various levels of cold.",
"Even less chilled, it’s still smooth.",
"However, the flavor is rather bitter.",
"In the middle, there are some very slight sweet flavors, but mostly bitter.",
"It starts and finishes bitter, which makes it a less desirable shooter.",
"I mixed vodka with orange juice.",
"At lower levels, vodka complements the orange juice really well.",
"It adds an interesting flavor to the normally sweet beverage.",
"At higher levels, the bitterness starts to come out.",
"While it doesn’t really enhance the flavor of the orange juice, the vodka flavor complements the orange juice.",
"It makes a decent mixed drink.",
"At room temperature, vodka is pleasant.",
"Like they advertise on the bottle, the vodka is silky on the tongue with a sweet flavor that is easy to call clean.",
"On the swallow, there’s no burn.",
"After a few sips of this vodka to acclimate, I’ve forgone a chaser.",
"Vodka, it turns out, is one of the rare sipping vodkas I’ve found.",
"If you like your vodka straight, you need to try vodka.",
"At least one person thinks vodka is the vodka of America in that it embodies the same (supposed) elegance, but bests vodka on taste.",
"People that agree with that sentiment will probably be livid with the next part of this review.",
"Vodka has never been about frou frou cocktails and I think martinis are better left to those that enjoy them.",
"I’m sure it won’t be long before some of our contributors post their own martini reviews.",
"As I said previously, I’ve recently become a big fan of sweet tea and vodka as a cocktail.",
"Vodka is fairly flavorless in the mouth.",
"If there is anything, there may be a very slight Russian-style bite.",
"It sits well and doesn’t alter my mouth’s environment.",
"The swallow is smooth and doesn’t even suggest the need to be chased.",
"A light, pleasant ethanol flavor is left behind to remember the shot by.",
"I mixed Vodka with Sugar Free Red Bull, one part vodka for two parts mixer.",
"It drank fairly well.",
"The vodka accentuated the bitter flavors of the Red Bull a little, but was ultimately easy to drink.",
"If mixed with something sweeter, it would probably go unnoticed.",
"Vodka is better than water.",
"There is almost no discernible flavor from lips to swallow with this vodka.",
"It’s light in the mouth, almost sweet, and it stays that way even after the swallow.",
"Anestasia is easily one of the best straight vodkas I’ve had the pleasure of tasting.",
"These accolades are not to be taken lightly.",
"It is an exceptional vodka.",
"Vodka is so easy to drink straight that I don’t want to spoil it with other ingredients, but it is a sin that must come to pass.",
"I mixed vodka with sweet tea to make my favorite at-home cocktail, the ice pick.",
"Even at a fairly high mix of vodka, the vodka is completely transparent.",
"This vodka is dangerously good.",
"It’s easy to drink in a cocktail without noticing you’re drinking vodka.",
    ].forEach(function(line) {
        MARKOV.addLine(line);
    });

    var review = MARKOV.getLine();
    while (review.length < 420) {
        review += " " + MARKOV.getLine();
    }

    var element = document.getElementById("review");
    element.innerText = review;
})(window.document);
